---
- hosts: all
  remote_user: admin
  become: yes           #<---Para que se pueda ejecutar como root
  tasks:
    - name: Add several users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        append: yes
        create_home: yes
        groups: "wheel"
        shell: /bin/bash
      loop:               #<---Usuarios que se van a agregar
         - dcarmar2
         - jvilman1
         - aseoros1
         - jgardie2
         - asanqui2

    - name: Delete several users
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
        remove: yes       #<---Indica que se va a eliminar el directorio personal
      loop:               #<---Usuarios que se van a eliminar
         - dcarmar2
