# -- PARTE DE APACHE -- #
---
# Mover recursos o Deshabilitar el nodo que se va a actualizar
# En el caso de los apache -> decirle a pacemaker (pcs) que deshabilite un nodo del cluster de los apache con community.general.pacemaker_cluster
# En el caso de los tomcat -> decirle al apache que mande todo a un nodo específico de tomcat con community.general.apache2_mod_proxy module


# Ponemos el nodo que se va a actualizar en offline(en este caso el server1)
- hosts: server1
  gather_facts: no
  tasks:
  - name: Set a node Offline(server1)
    community.general.pacemaker_cluster:
      state: offline

# Actualizamos el nodo que esta offline
- hosts: server1
  remote_user: admin
  become: yes
  tasks:
    - name: Actualizar nodo(server1)
      yum: name=* state=latest      

# Volvemos a poner el nodo online una vez actualizado 
- hosts: server1
  gather_facts: no
  tasks:
  - name: Set a node Online(server1)
    community.general.pacemaker_cluster:
      state: online

# Esperamos un tiempo para que el pacemaker reconozca que el nodo esta online
- hosts: server2
  remote_user: admin
  become: yes
  tasks:
    - name: esperador
      shell: sleep 60 #Tiempo de espera en segundos que creemos necesario para que el cluster vuelva a poder cambiar los recursos de nodo.

# Ponemos el nodo que se va a actualizar en offline(en este caso el server2)
- hosts: server2
  gather_facts: no
  tasks:
  - name: Set a node Offline(server2)
    community.general.pacemaker_cluster:
      state: offline

# Actualizamos el nodo que esta offline
- hosts: server2
  remote_user: admin
  become: yes
  tasks:
    - name: Actualizar nodo(server2)
      yum: name=* state=latest      

# Volvemos a poner el nodo online una vez actualizado 
- hosts: server2
  gather_facts: no
  tasks:
  - name: Set a node Online(server2)
    community.general.pacemaker_cluster:
      state: online



# -- PARTE DE TOMCAT -- #

#Actualizamos un nodo
- hosts: server3
  remote_user: admin
  become: yes
  tasks:
    - name: Step 1
      community.general.apache2_mod_proxy:
        balancer_vhost: '{{ vhost_host }}' # (ipv4|ipv6|fqdn):port of the Apache httpd 2.4 mod_proxy balancer pool.
        member_host: '{{ member.host }}' # (ipv4|ipv6|fqdn) of the balancer member to get or to set attributes to. Port number is autodetected and should not be specified here.
        state: drained
    - name: Step 2
      ansible.builtin.wait_for:
        host: '{{ member.host }}' 
        port: '{{ member.port }}' 
        state: drained
    - name: Step 3
      community.general.apache2_mod_proxy:
        balancer_vhost: '{{ vhost_host }}' # (ipv4|ipv6|fqdn):port of the Apache httpd 2.4 mod_proxy balancer pool.
        member_host: '{{ member.host }}' # (ipv4|ipv6|fqdn) of the balancer member to get or to set attributes to. Port number is autodetected and should not be specified here.
        state: absent
    - name: Escribir mensaje
      yum: name=* state=latest 
    - name: Step 3
      community.general.apache2_mod_proxy:
        balancer_vhost: '{{ vhost_host }}' # (ipv4|ipv6|fqdn):port of the Apache httpd 2.4 mod_proxy balancer pool.
        member_host: '{{ member.host }}'  # (ipv4|ipv6|fqdn) of the balancer member to get or to set attributes to. Port number is autodetected and should not be specified here.
        state: present


#Actualizamos el otro nodo
- hosts: server4
  remote_user: admin
  become: yes
  tasks:
    - name: Step 1
      community.general.apache2_mod_proxy:
        balancer_vhost: '{{ vhost_host }}' # (ipv4|ipv6|fqdn):port of the Apache httpd 2.4 mod_proxy balancer pool.
        member_host: '{{ member.host }}' # (ipv4|ipv6|fqdn) of the balancer member to get or to set attributes to. Port number is autodetected and should not be specified here.
        state: drained
    - name: Step 2
      ansible.builtin.wait_for:
        host: '{{ member.host }}' 
        port: '{{ member.port }}' 
        state: drained
      delegate_to: myloadbalancernode
    - name: Step 3
      community.general.apache2_mod_proxy:
        balancer_vhost: '{{ vhost_host }}' # (ipv4|ipv6|fqdn):port of the Apache httpd 2.4 mod_proxy balancer pool.
        member_host: '{{ member.host }}' # (ipv4|ipv6|fqdn) of the balancer member to get or to set attributes to. Port number is autodetected and should not be specified here.
        state: absent
    - name: Escribir mensaje
      yum: name=* state=latest 
    - name: Step 3
      community.general.apache2_mod_proxy:
      balancer_vhost: '{{ vhost_host }}'
      member_host: '{{ member.host }}'
      state: present
